package workspacetransfer

import (
	"bufio"
	"context"
	"fmt"
	"os"
	"path/filepath"
	"slices"
	"strconv"
	"strings"
	"sync"
	"sync/atomic"
	"testing"

	"github.com/wedevwork/callsheet/internal/contract"
)

// Code review r5: Callsheet refuses every configuration value that makes
// git status fail, for every key, and refuses no value Git accepts except
// for its documented policies. testdata/gitconfig_oracle.tsv is Git
// 2.43.0's verdict on every key of `git help --config` (and the
// repository extensions) with malformed values, regenerated by
// gitoracle_gen_test.go (build tag gitoracle; never run in CI).

type oracleRow struct {
	key, ctx, value string
	noValue, accept bool
}

// oracleLoads counts parseOracle calls in this process
// (TestOracleInputsPerUse requires one).
var oracleLoads atomic.Int64

// parseOracle expands testdata/gitconfig_oracle.tsv into its rows (more
// than 30,000).
func parseOracle() ([]oracleRow, error) {
	oracleLoads.Add(1)
	f, err := os.Open(filepath.Join("testdata", "gitconfig_oracle.tsv"))
	if err != nil {
		return nil, err
	}
	defer f.Close()
	values := func(l string) ([]string, error) {
		var out []string
		for rest := l; rest != ""; {
			rest = strings.TrimLeft(rest, " ")
			if v, ok := strings.CutPrefix(rest, "<novalue>"); ok {
				out, rest = append(out, "<novalue>"), v
				continue
			}
			q, err := strconv.QuotedPrefix(rest)
			if err != nil {
				return nil, fmt.Errorf("bad oracle header %q", l)
			}
			v, _ := strconv.Unquote(q)
			out, rest = append(out, v), rest[len(q):]
		}
		return out, nil
	}
	var standard, vocabulary []string
	var rows []oracleRow
	sc := bufio.NewScanner(f)
	sc.Buffer(make([]byte, 64<<10), 1<<20)
	for sc.Scan() {
		l := sc.Text()
		switch {
		case strings.HasPrefix(l, "# standard values: "):
			if standard, err = values(strings.TrimPrefix(l, "# standard values: ")); err != nil {
				return nil, err
			}
			continue
		case strings.HasPrefix(l, "# vocabulary: "):
			if vocabulary, err = values(strings.TrimPrefix(l, "# vocabulary: ")); err != nil {
				return nil, err
			}
			continue
		case strings.HasPrefix(l, "#"):
			continue
		}
		p := strings.Split(l, "\t")
		all := append(append([]string(nil), standard...), vocabulary...)
		if len(p) != 3 || (len(p[2]) != len(standard) && len(p[2]) != len(all)) {
			return nil, fmt.Errorf("bad oracle row %q", l)
		}
		for i, v := range p[2] {
			r := oracleRow{key: p[0], ctx: p[1], value: all[i], accept: v == 'A'}
			if r.value == "<novalue>" {
				r.value, r.noValue = "", true
			}
			rows = append(rows, r)
		}
	}
	if err := sc.Err(); err != nil {
		return nil, err
	}
	if len(standard) != 7 || len(vocabulary) < 100 || len(rows) < 30000 {
		return nil, fmt.Errorf("oracle table truncated: %d standard, %d vocabulary values, %d rows", len(standard), len(vocabulary), len(rows))
	}
	return rows, nil
}

// oracleTable is the process's parsed oracle table.
var oracleTable = sync.OnceValues(parseOracle)

// loadOracle returns a fresh copy of the oracle table. The table, and the
// push cases derived from it (oraclePushCases), are a pure function of
// testdata: parsing them is a fixed prefix the stress stage would
// otherwise pay on every repetition although the sampler already spreads
// the rows over the repetitions, so they are parsed once per process and
// every use gets its own copy (oracleRow holds only strings and bools, so
// a slice copy is a deep copy): a mutation in one use cannot reach the
// next (TestOracleInputsPerUse). Only the input is shared; every row
// check and push runs as before.
func loadOracle(t testing.TB) []oracleRow {
	t.Helper()
	rows, err := oracleTable()
	if err != nil {
		t.Fatal(err)
	}
	return slices.Clone(rows)
}

// derivePushCases is TestGitConfigOraclePush's case list: one refused
// value of every key and context Git refuses, every 151st accepted row,
// and the reviewer's cases.
func derivePushCases() ([]oracleRow, error) {
	rows, err := oracleTable()
	if err != nil {
		return nil, err
	}
	var cases []oracleRow
	seen := map[string]bool{}
	for i, r := range rows {
		switch {
		case !r.accept && !seen[r.key+"\x00"+r.ctx]:
			seen[r.key+"\x00"+r.ctx] = true
			cases = append(cases, r)
		case r.accept && i%151 == 0:
			cases = append(cases, r)
		}
	}
	// The reviewer's cases.
	cases = append(cases,
		oracleRow{key: "extensions.preciousObjects", ctx: "v1", value: "0\v"},
		oracleRow{key: "core.safecrlf", ctx: "v0", value: "0\v"},
		oracleRow{key: "core.logAllRefUpdates", ctx: "v0", value: "0\v"},
		oracleRow{key: "core.protectHFS", ctx: "v0", value: "0\v"},
		oracleRow{key: "core.sparseCheckoutCone", ctx: "v0", value: "0\v"},
	)
	return cases, nil
}

// oraclePushTable is the process's push case list.
var oraclePushTable = sync.OnceValues(derivePushCases)

// oraclePushCases returns a fresh copy of the push case list.
func oraclePushCases(t testing.TB) []oracleRow {
	t.Helper()
	cases, err := oraclePushTable()
	if err != nil {
		t.Fatal(err)
	}
	return slices.Clone(cases)
}

// TestOracleInputsPerUse proves the oracle table and the push case list
// are parsed once per process and copied per use: each repetition
// overwrites its copies with zero rows, which no table holds (every row
// has a key), and both a second copy in the same repetition and the first
// copy of every later repetition (-count) must hold none of them.
func TestOracleInputsPerUse(t *testing.T) {
	clean := func(name string, rows []oracleRow, want int) {
		t.Helper()
		if len(rows) != want {
			t.Fatalf("%s: %d rows, want %d", name, len(rows), want)
		}
		for i := range rows {
			if rows[i].key == "" {
				t.Fatalf("%s: row %d is %+v: a use's mutation reached another use", name, i, rows[i])
			}
		}
	}
	for _, in := range []struct {
		name string
		get  func(testing.TB) []oracleRow
	}{{"oracle table", loadOracle}, {"push cases", oraclePushCases}} {
		first := in.get(t)
		n := len(first)
		clean(in.name, first, n)
		clear(first)
		again := in.get(t)
		clean(in.name, again, n)
		if &again[0] == &first[0] {
			t.Fatalf("%s: two uses share one slice", in.name)
		}
	}
	if n := oracleLoads.Load(); n != 1 {
		t.Fatalf("the oracle table was parsed %d times in this process, want once", n)
	}
}

// line is the row's configuration text (the generator's oracleLine).
func (r oracleRow) line() string {
	sec, rest, _ := strings.Cut(r.key, ".")
	name, hdr := rest, "["+sec+"]"
	if i := strings.LastIndexByte(rest, '.'); i >= 0 {
		hdr, name = "["+sec+" \""+rest[:i]+"\"]", rest[i+1:]
	}
	if r.noValue {
		return hdr + "\n\t" + name + "\n"
	}
	return hdr + "\n\t" + name + " = \"" + strings.NewReplacer(`\`, `\\`, `"`, `\"`).Replace(r.value) + "\"\n"
}

// policyRefusal reports a row Callsheet refuses although Git accepts it:
// the documented unsupported features (per-worktree configuration,
// core.worktree, partial clones, SHA-256, sparse checkout, configured
// submodules, a negative repository format version).
func policyRefusal(r oracleRow) bool {
	k := normalizeKey(r.key)
	repo := r.ctx == "v0" || r.ctx == "v1"
	truthy := func() bool {
		if r.noValue {
			return true
		}
		b, err := parseGitBool(r.value)
		return err == nil && b
	}
	switch {
	case r.ctx == "worktree":
		return true
	case k == "core.worktree" && repo, k == "extensions.partialclone" && repo:
		return true
	case k == "extensions.worktreeconfig" && repo && truthy():
		return true
	case k == "extensions.objectformat" && r.ctx == "v1" && r.value == "sha256":
		return true
	case k == "core.sparsecheckout" && truthy():
		return true
	case strings.HasPrefix(k, "remote.") && (strings.HasSuffix(k, ".promisor") || strings.HasSuffix(k, ".partialclonefilter")):
		return true
	case strings.HasPrefix(k, "submodule.") && strings.Count(k, ".") >= 2:
		return true
	case k == "core.repositoryformatversion" && repo && !r.noValue:
		n, ok := parseGitInt(r.value, 1<<31-1)
		return ok && n < 0
	}
	return false
}

// baseFor is the repository configuration of a context.
func baseFor(ctx string) string {
	v := "0"
	if ctx == "v1" || ctx == "worktree" {
		v = "1"
	}
	base := "[core]\n\trepositoryformatversion = " + v + "\n\tfilemode = true\n\tbare = false\n"
	switch ctx {
	case "include":
		base += "[include]\n\tpath = included.cfg\n"
	case "worktree":
		base += "[extensions]\n\tworktreeConfig = true\n"
	}
	return base
}

// TestGitConfigOracleRules checks every row of the table against the
// configuration checks (the parsed entries of the row's context).
func TestGitConfigOracleRules(t *testing.T) {
	run := sampler(t)
	for i, r := range loadOracle(t) {
		if !run(i) || r.ctx == "worktree" || normalizeKey(r.key) == "include.path" {
			continue // per-worktree configuration and includes: TestGitConfigOraclePush
		}
		c := &gitConfig{}
		add := func(text string, repo bool) {
			if err := parseGitConfig([]byte(text), func(sec, sub, name, value string, blank bool) error {
				c.entries = append(c.entries, configEntry{key: configKey(sec, sub, name), value: value, blank: blank, repo: repo})
				return nil
			}); err != nil {
				t.Fatalf("%+v: %v", r, err)
			}
		}
		add(baseFor(r.ctx), true)
		add(r.line(), r.ctx == "v0" || r.ctx == "v1")
		err := checkConfig(c)
		want := r.accept && !policyRefusal(r)
		if want != (err == nil) {
			t.Errorf("%s (%s) = %q (novalue %v): Git %v, policy refusal %v; Callsheet: %v", r.key, r.ctx, r.value, r.noValue,
				map[bool]string{true: "accepts", false: "refuses"}[r.accept], policyRefusal(r), err)
		}
	}
}

// TestGitConfigOraclePush pushes through the production entry point: one
// refused value of every key and context Git refuses, and a sample of the
// accepted rows, in the value's real place (.git/config, an included
// file, the global configuration or .git/config.worktree).
func TestGitConfigOraclePush(t *testing.T) {
	cases := oraclePushCases(t)
	root, home := oraclePushFixture(t)
	env := envOf(map[string]string{"HOME": home, "GIT_CONFIG_NOSYSTEM": "1"})
	run := sampler(t)
	for i, c := range cases {
		if !run(i) {
			continue
		}
		files := map[string]string{filepath.Join(root, ".git/config"): baseFor(c.ctx), filepath.Join(root, ".git/included.cfg"): "",
			filepath.Join(home, ".gitconfig"): "", filepath.Join(root, ".git/config.worktree"): ""}
		switch c.ctx {
		case "v0", "v1":
			files[filepath.Join(root, ".git/config")] += c.line()
		case "include":
			files[filepath.Join(root, ".git/included.cfg")] = c.line()
		case "global":
			files[filepath.Join(home, ".gitconfig")] = c.line()
		case "worktree":
			files[filepath.Join(root, ".git/config.worktree")] = c.line()
		}
		for p, s := range files {
			if err := os.WriteFile(p, []byte(s), 0o644); err != nil {
				t.Fatal(err)
			}
		}
		_, err := fastDeps().push(context.Background(), Options{GOOS: "linux", Env: env, Cwd: "/", Plane: &localPlane{t: t}},
			PushRequest{Name: "ws", Instance: tInst, Path: root, PathSet: true})
		want := c.accept && !policyRefusal(c)
		switch {
		case want && err != nil:
			t.Errorf("%s (%s) = %q: Git accepts it, Push refused: %v", c.key, c.ctx, c.value, err)
		case !want && err == nil:
			t.Errorf("%s (%s) = %q (novalue %v): Git refuses it, Push accepted", c.key, c.ctx, c.value, c.noValue)
		case !want && contract.TransferReason(err) != contract.ReasonUnsupportedRepository:
			t.Errorf("%s (%s) = %q: refused with %v, want unsupported_repository", c.key, c.ctx, c.value, err)
		}
	}
}

// oraclePushRepo is TestGitConfigOraclePush's repository and HOME, built
// once per process (committing the repository on every repetition was a
// fixed prefix of the stress stage). Push leaves its source repository
// unchanged, and every case rewrites all four configuration files it
// reads (.git/config, .git/included.cfg, ~/.gitconfig and
// .git/config.worktree) before its push, so the cases of one repetition
// already share one repository. Across repetitions, each repetition's
// cleanup restores those files and the next one first requires the
// repository and HOME to match their fingerprint taken when they were
// built.
var oraclePushRepo struct {
	once       sync.Once
	dir, print string
	root, home string
}

// oraclePushFixture returns the process's push repository root and HOME,
// unchanged since they were built.
func oraclePushFixture(t *testing.T) (root, home string) {
	t.Helper()
	o := &oraclePushRepo
	o.once.Do(func() {
		dir := processDir(t)
		repo := newRepoAt(t, filepath.Join(dir, "repo"), map[string]fspec{"f": reg("f\n")})
		home := filepath.Join(dir, "home")
		if err := os.Mkdir(home, 0o700); err != nil {
			t.Fatal(err)
		}
		o.dir, o.root, o.home, o.print = dir, repo.root, home, fingerprint(t, dir)
	})
	if o.root == "" {
		t.Fatal("the oracle push repository failed to build in an earlier repetition")
	}
	if fingerprint(t, o.dir) != o.print {
		t.Fatal("the oracle push repository or HOME changed since it was built")
	}
	t.Cleanup(func() {
		if err := os.WriteFile(filepath.Join(o.root, ".git/config"), []byte(baseConfig), 0o644); err != nil {
			t.Error(err)
		}
		for _, p := range []string{filepath.Join(o.root, ".git/included.cfg"), filepath.Join(o.home, ".gitconfig"), filepath.Join(o.root, ".git/config.worktree")} {
			if err := os.Remove(p); err != nil && !os.IsNotExist(err) {
				t.Error(err)
			}
		}
	})
	return o.root, o.home
}

// TestGitValueParsers covers the special parsers directly.
func TestGitValueParsers(t *testing.T) {
	for _, c := range []struct {
		v  string
		ok bool
	}{
		{"", true}, {"red", true}, {"Red BOLD", false}, {"red bold", true}, {"bold red", true}, {"red blue", true}, {"red blue green", false},
		{"#ff0000", true}, {"#ff00zz", false}, {"#fff", false}, {"brightred", true}, {"BrightRed", true}, {"bright", false}, {"-1", true},
		{"-2", false}, {"255", true}, {"256", false}, {"+5", true}, {"nobold", true}, {"no-ul", true}, {"no", false}, {"reset red", true},
		{"normal default", true}, {" \tred\r\n", true}, {"red\vbold", false},
	} {
		if colorParses(c.v) != c.ok {
			t.Errorf("color %q: %v", c.v, !c.ok)
		}
	}
	if !gitPerm("0640", false) || gitPerm("0440", false) || !gitPerm("x", false) == gitBool("x", false) || !gitPerm("-1", false) {
		t.Error("core.sharedRepository")
	}
	if u, ok := parseGitUnsigned("18446744073709551615"); !ok || u != 1<<64-1 {
		t.Errorf("max uint64: %d %v", u, ok)
	}
	for _, v := range []string{"18446744073709551616", "1t", "", "0x", "17179869184G"} {
		if _, ok := parseGitUnsigned(v); ok {
			t.Errorf("unsigned %q accepted", v)
		}
	}
	if n, rest := strtol("99999999999999999999", 10); n != 1<<63-1 || rest != "" {
		t.Errorf("strtol saturation %d %q", n, rest)
	}
	if n, rest := strtol("-99999999999999999999", 10); n != -1<<63 || rest != "" {
		t.Errorf("strtol negative saturation %d %q", n, rest)
	}
	if gitColorMovedWS("allow-indentation-change,ignore-all-space", false) || !gitColorMovedWS("no , ignore-all-space", false) {
		t.Error("colorMovedWS")
	}
	if gitWSErrorHighlight("allX", false) || gitWSErrorHighlight("newold", false) || gitWSErrorHighlight("new;old", false) ||
		!gitWSErrorHighlight("new,old", false) || !gitWSErrorHighlight("new,", false) || gitWSErrorHighlight("new,,old", false) {
		t.Error("wsErrorHighlight")
	}
	if ruleFor("nosection") != nil || ruleFor("diff.binary") != nil || ruleFor("diff.My Driver.binary") == nil {
		t.Error("ruleFor")
	}
}

// TestConfigOverriddenInvalidValue: an invalid value is refused even when
// a later valid one overrides it (Git fails on every occurrence).
func TestConfigOverriddenInvalidValue(t *testing.T) {
	env := emptyEnv(t)
	for _, c := range []struct{ base, sec, name, good string }{
		{"1", "extensions", "preciousObjects", "true"}, {"0", "core", "safecrlf", "warn"}, {"0", "core", "logAllRefUpdates", "always"},
		{"0", "core", "protectHFS", "false"}, {"0", "core", "sparseCheckoutCone", "true"}, {"0", "color", "ui", "auto"},
		{"0", "status", "showUntrackedFiles", "normal"},
	} {
		r := newRepo(t, map[string]fspec{"f": reg("f\n")})
		mustWrite(t, filepath.Join(r.root, ".git/config"), "[core]\n\trepositoryformatversion = "+c.base+"\n"+
			"["+c.sec+"]\n\t"+c.name+" = 0\v\n["+c.sec+"]\n\t"+c.name+" = "+c.good+"\n")
		if err := pushLocal(t, r.root, env); contract.TransferReason(err) != contract.ReasonUnsupportedRepository {
			t.Errorf("%s.%s overridden: %v", c.sec, c.name, err)
		}
		mustWrite(t, filepath.Join(r.root, ".git/config"), "[core]\n\trepositoryformatversion = "+c.base+"\n["+c.sec+"]\n\t"+c.name+" = "+c.good+"\n")
		if err := pushLocal(t, r.root, env); err != nil {
			t.Errorf("%s.%s valid: %v", c.sec, c.name, err)
		}
	}
}
