package workspacetransfer

import (
	"math"
	"strings"

	"github.com/wedevwork/callsheet/internal/contract"
)

// Git's configuration value rules. Callsheet refuses every repository
// whose configuration makes git status fail, for every key: the keys and
// their rules below are those of Git 2.43.0 found by the checked-in
// oracle (testdata/gitconfig_oracle.tsv, every key of `git help --config`
// with malformed values, regenerated by gitoracle_gen_test.go), and each
// rule is Git's own parser for that key. A key Git does not validate is
// never refused for its value. Every occurrence is checked, in every
// configuration file Git reads (system, global, the repository's,
// includes), because Git fails on any of them. The repository-format
// keys (core.repositoryFormatVersion, extensions.*, core.worktree and a
// true core.bare) are checked by checkConfig from .git/config only, where
// Git reads them.

// valueRule reports whether Git accepts value (blank: written without
// "=", Git's NULL value).
type valueRule func(value string, blank bool) bool

// gitBool is git_config_bool (blank is true).
func gitBool(v string, blank bool) bool {
	if blank {
		return true
	}
	_, err := parseGitBool(v)
	return err == nil
}

// nonBool is a string Git requires a value for (config_error_nonbool).
func nonBool(_ string, blank bool) bool { return !blank }

// gitInt is git_config_int: an int in the C int range.
func gitInt(v string, blank bool) bool {
	_, ok := parseGitInt(v, math.MaxInt32)
	return !blank && ok
}

// gitIntRange is git_config_int bounded to [lo, hi].
func gitIntRange(lo, hi int64) valueRule {
	return func(v string, blank bool) bool {
		n, ok := parseGitInt(v, math.MaxInt32)
		return !blank && ok && n >= lo && n <= hi
	}
}

// gitUlong is git_config_ulong (git_parse_unsigned): no '-' anywhere, an
// unsigned 64-bit value after strtoumax and a k/m/g unit.
func gitUlong(v string, blank bool) bool {
	if blank || v == "" || strings.IndexByte(v, '-') >= 0 {
		return false
	}
	_, ok := parseGitUnsigned(v)
	return ok
}

// boolOr accepts the keywords (compared with match) or a Git boolean.
func boolOr(fold bool, words ...string) valueRule {
	return func(v string, blank bool) bool {
		if !blank && matchWord(v, fold, words) {
			return true
		}
		return gitBool(v, blank)
	}
}

// oneOf accepts exactly the keywords (a value is required).
func oneOf(fold bool, words ...string) valueRule {
	return func(v string, blank bool) bool { return !blank && matchWord(v, fold, words) }
}

func matchWord(v string, fold bool, words []string) bool {
	for _, w := range words {
		if v == w || fold && asciiFold(v) == w {
			return true
		}
	}
	return false
}

// gitColorBool is git_config_colorbool: never, always, auto (any case)
// or a boolean.
var gitColorBool = boolOr(true, "never", "always", "auto")

// gitAbbrev is core.abbrev: a value is required; "auto" (any case); a
// false word (git_parse_maybe_bool_text) is the full length; otherwise an
// int from 4 to 40.
func gitAbbrev(v string, blank bool) bool {
	if blank {
		return false
	}
	switch asciiFold(v) {
	case "auto", "false", "no", "off", "":
		return true
	}
	n, ok := parseGitInt(v, math.MaxInt32)
	return ok && n >= 4 && n <= 40
}

// gitCommentChar is core.commentChar: "auto" (any case) or one byte.
func gitCommentChar(v string, blank bool) bool {
	return !blank && (asciiFold(v) == "auto" || len(v) == 1)
}

// gitPerm is core.sharedRepository (git_config_perm).
func gitPerm(v string, blank bool) bool {
	if blank {
		return true
	}
	switch v {
	case "umask", "group", "all", "world", "everybody":
		return true
	}
	n, rest := strtol(v, 8)
	if rest != "" {
		return gitBool(v, false)
	}
	i := int32(n) // C assigns the long to an int
	switch i {
	case 0, 1, 2:
		return true
	}
	return i&0o600 == 0o600
}

// gitColor is a color slot (git_config_color): a value is required and
// must parse as color_parse_mem does.
func gitColor(v string, blank bool) bool { return !blank && colorParses(v) }

// gitColumn is column.* (git_config_column's parse_config): words
// separated by spaces or commas, each always, never, auto, plain, column,
// row, dense or nodense. A value is required.
func gitColumn(v string, blank bool) bool {
	if blank {
		return false
	}
	for _, w := range strings.FieldsFunc(v, func(r rune) bool { return r == ' ' || r == ',' }) {
		switch w {
		case "always", "never", "auto", "plain", "column", "row", "dense", "nodense":
		default:
			return false
		}
	}
	return true
}

// gitColorMovedWS is diff.colorMovedWS (parse_color_moved_ws).
func gitColorMovedWS(v string, blank bool) bool {
	if blank {
		return false
	}
	indent, ws := false, false
	for _, w := range strings.Split(v, ",") {
		switch strings.Trim(w, " \t\n\r") {
		case "no":
			indent, ws = false, false
		case "ignore-space-change", "ignore-space-at-eol", "ignore-all-space":
			ws = true
		case "allow-indentation-change":
			indent = true
		default:
			return false
		}
	}
	return !(indent && ws)
}

// gitWSErrorHighlight is diff.wsErrorHighlight
// (parse_ws_error_highlight): keywords matched as prefixes, each followed
// by the end of the value or a comma (a trailing comma ends the list).
func gitWSErrorHighlight(v string, blank bool) bool {
	if blank {
		return false
	}
	for v != "" {
		matched := false
		for _, w := range []string{"none", "default", "all", "new", "old", "context"} {
			if strings.HasPrefix(v, w) {
				v, matched = v[len(w):], true
				break
			}
		}
		if !matched {
			return false
		}
		// More input must follow a comma.
		if v != "" {
			if v[0] != ',' {
				return false
			}
			v = v[1:]
		}
	}
	return true
}

// gitColorMoved is diff.colorMoved (parse_color_moved).
func gitColorMoved(v string, blank bool) bool {
	if blank {
		return true
	}
	if _, err := parseGitBool(v); err == nil {
		return true
	}
	switch v {
	case "no", "plain", "blocks", "zebra", "default", "dimmed-zebra", "dimmed_zebra":
		return true
	}
	return false
}

// configRules maps a normalized key (section and name lowercased, the
// subsection as written) to Git's rule.
var configRules = func() map[string]valueRule {
	m := map[string]valueRule{}
	set := func(r valueRule, keys ...string) {
		for _, k := range keys {
			m[normalizeKey(k)] = r
		}
	}
	set(gitBool, "advice.addEmbeddedRepo", "advice.addEmptyPathspec", "advice.addIgnoredFile", "advice.amWorkDir",
		"advice.ambiguousFetchRefspec", "advice.checkoutAmbiguousRemoteBranchName", "advice.commitBeforeMerge", "advice.detachedHead",
		"advice.diverging", "advice.fetchShowForcedUpdates", "advice.graftFileDeprecated", "advice.ignoredHook", "advice.implicitIdentity",
		"advice.nestedTag", "advice.objectNameWarning", "advice.pushAlreadyExists", "advice.pushFetchFirst", "advice.pushNeedsForce",
		"advice.pushNonFFCurrent", "advice.pushNonFFMatching", "advice.pushNonFastForward", "advice.pushRefNeedsUpdate",
		"advice.pushUnqualifiedRefName", "advice.pushUpdateRejected", "advice.resetNoRefresh", "advice.resolveConflict", "advice.rmHints",
		"advice.sequencerInUse", "advice.setUpstreamFailure", "advice.skippedCherryPicks", "advice.statusAheadBehindWarning",
		"advice.statusHints", "advice.statusUoption", "advice.submoduleAlternateErrorStrategyDie", "advice.submodulesNotUpdated",
		"advice.suggestDetachingHead", "advice.updateSparsePath", "advice.waitingForEditor", "advice.worktreeAddOrphan", "color.pager",
		"commitGraph.readChangedPaths", "core.commitGraph", "core.fileMode", "core.fsyncObjectFiles", "core.ignoreCase", "core.ignoreStat",
		"core.multiPackIndex", "core.precomposeUnicode", "core.preferSymlinkRefs", "core.preloadIndex", "core.protectHFS",
		"core.protectNTFS", "core.quotePath", "core.sparseCheckout", "core.sparseCheckoutCone", "core.symlinks", "core.trustctime",
		"core.useReplaceRefs", "core.warnAmbiguousRefs", "diff.autoRefreshIndex", "diff.indentHeuristic", "diff.mnemonicPrefix",
		"diff.noprefix", "diff.relative", "diff.suppressBlankEmpty", "feature.experimental", "feature.manyFiles", "fetch.writeCommitGraph",
		"gc.writeCommitGraph", "index.skipHash", "index.sparse", "index.threads", "pack.readReverseIndex", "pack.useBitmapBoundaryTraversal",
		"pack.useSparse", "sparse.expectFilesOutsideOfPatterns", "status.aheadBehind", "status.branch", "status.displayCommentPrefix",
		"status.relativePaths", "status.short", "status.showStash", "status.submoduleSummary", "user.useConfigOnly",
		// core.bare's value is checked everywhere; a true one counts only
		// in .git/config (checkConfig).
		"core.bare")
	set(nonBool, "attr.tree", "author.email", "author.name", "committer.email", "committer.name", "core.askPass", "core.attributesFile",
		"core.checkRoundtripEncoding", "core.checkStat", "core.editor", "core.excludesFile", "core.fsync", "core.fsyncMethod",
		"core.hooksPath", "core.notesRef", "core.untrackedCache", "core.whitespace", "diff.dirstat", "diff.external", "diff.orderFile",
		"diff.submodule", "diff.wordRegex", "i18n.commitEncoding", "i18n.logOutputEncoding", "mailmap.blob", "mailmap.file",
		"user.email", "user.name")
	set(gitColor, "color.advice.hint", "color.status.added", "color.status.branch", "color.status.changed", "color.status.header",
		"color.status.localBranch", "color.status.noBranch", "color.status.remoteBranch", "color.status.unmerged",
		"color.status.untracked", "color.status.updated")
	for _, slot := range []string{"commit", "context", "contextBold", "contextDimmed", "frag", "func", "meta", "new", "newBold",
		"newDimmed", "newMoved", "newMovedAlternative", "newMovedAlternativeDimmed", "newMovedDimmed", "old", "oldBold", "oldDimmed",
		"oldMoved", "oldMovedAlternative", "oldMovedAlternativeDimmed", "oldMovedDimmed", "plain", "whitespace"} {
		set(gitColor, "color.diff."+slot)
	}
	set(gitInt, "commitGraph.generationVersion", "diff.renameLimit", "diff.statGraphWidth", "diff.statNameWidth", "index.version",
		"status.renameLimit")
	set(gitUlong, "core.bigFileThreshold", "core.deltaBaseCacheLimit", "core.packedGitLimit", "core.packedGitWindowSize",
		"pack.packSizeLimit")
	set(gitColorBool, "color.advice", "color.diff", "color.status", "color.ui")
	set(gitIntRange(-1, 9), "core.compression", "core.looseCompression", "pack.compression")
	set(gitIntRange(0, math.MaxInt32), "core.maxTreeDepth", "diff.context", "diff.interHunkContext")
	set(gitColumn, "column.status", "column.ui")
	set(boolOr(true, "copies", "copy"), "diff.renames", "status.renames")
	set(boolOr(false, "always", "inherit", "simple"), "branch.autoSetupMerge")
	set(oneOf(false, "never", "local", "remote", "always"), "branch.autoSetupRebase")
	set(gitAbbrev, "core.abbrev")
	set(boolOr(true, "input"), "core.autocrlf")
	set(gitCommentChar, "core.commentChar")
	set(oneOf(false, "rename", "link"), "core.createObject")
	set(boolOr(true, "always"), "core.logAllRefUpdates")
	set(boolOr(true, "warn"), "core.safecrlf")
	set(gitPerm, "core.sharedRepository")
	set(oneOf(true, "myers", "default", "minimal", "patience", "histogram"), "diff.algorithm")
	set(gitColorMoved, "diff.colorMoved")
	set(gitColorMovedWS, "diff.colorMovedWS")
	set(oneOf(false, "none", "untracked", "dirty", "all"), "diff.ignoreSubmodules")
	set(gitWSErrorHighlight, "diff.wsErrorHighlight")
	set(oneOf(true, "consecutive", "skipping", "noop", "default"), "fetch.negotiationAlgorithm")
	set(oneOf(false, "nothing", "current", "upstream", "tracking", "simple", "matching"), "push.default")
	set(oneOf(false, "no", "normal", "all"), "status.showUntrackedFiles")
	return m
}()

// subsectionRules are keys "section.<any>.name" Git validates for every
// subsection.
var subsectionRules = map[string]valueRule{
	"diff.binary":               boolOr(true, "auto"),
	"diff.cachetextconv":        gitBool,
	"diff.command":              nonBool,
	"diff.textconv":             nonBool,
	"diff.wordregex":            nonBool,
	"diff.xfuncname":            nonBool,
	"remote.promisor":           gitBool,
	"remote.partialclonefilter": nonBool,
}

// repoFormatKeys are checked from .git/config only (checkConfig).
var repoFormatKeys = map[string]bool{"core.repositoryformatversion": true, "core.worktree": true}

// ruleFor returns Git's rule for a normalized key, if Git validates it.
func ruleFor(key string) valueRule {
	if r, ok := configRules[key]; ok {
		return r
	}
	sec, rest, ok := strings.Cut(key, ".")
	if !ok {
		return nil
	}
	i := strings.LastIndexByte(rest, '.')
	if i < 0 {
		return nil
	}
	return subsectionRules[sec+"."+rest[i+1:]]
}

// validateGitConfig refuses a configuration with any value Git refuses.
func validateGitConfig(c *gitConfig) error {
	for _, e := range c.entries {
		if repoFormatKeys[e.key] || strings.HasPrefix(e.key, "extensions.") {
			continue
		}
		if r := ruleFor(e.key); r != nil && !r(e.value, e.blank) {
			return unsupportedConfig("the value of " + contract.SafeText(e.key, 64) + " is invalid for Git")
		}
	}
	return nil
}

// parseGitUnsigned is git_parse_unsigned's numeric part: strtoumax in base
// 0 (C isspace skipped, '+' allowed) and a k, m or g unit, in uint64.
func parseGitUnsigned(v string) (uint64, bool) {
	n, ok := parseGitInt(v, math.MaxInt64)
	if ok {
		return uint64(n), true
	}
	// Beyond int64: parse as unsigned.
	i := 0
	for i < len(v) && strings.IndexByte(" \t\n\v\f\r", v[i]) >= 0 {
		i++
	}
	if i < len(v) && v[i] == '+' {
		i++
	}
	base := uint64(10)
	switch {
	case i+2 < len(v) && v[i] == '0' && (v[i+1] == 'x' || v[i+1] == 'X') && hexDigit(v[i+2]) >= 0:
		base = 16
		i += 2
	case i < len(v) && v[i] == '0':
		base = 8
	}
	start := i
	var u uint64
	for ; i < len(v); i++ {
		d := hexDigit(v[i])
		if d < 0 || uint64(d) >= base {
			break
		}
		if u > (math.MaxUint64-uint64(d))/base {
			return 0, false
		}
		u = u*base + uint64(d)
	}
	if i == start {
		return 0, false
	}
	factor := uint64(1)
	switch v[i:] {
	case "":
	case "k", "K":
		factor = 1 << 10
	case "m", "M":
		factor = 1 << 20
	case "g", "G":
		factor = 1 << 30
	default:
		return 0, false
	}
	if u > math.MaxUint64/factor {
		return 0, false
	}
	return u * factor, true
}

// strtol is C's strtol in base 8 or 10 for the C locale: leading C
// isspace, a sign, digits (saturating); rest is what follows the digits
// (the whole input when there are none).
func strtol(v string, base int64) (int64, string) {
	i := 0
	for i < len(v) && strings.IndexByte(" \t\n\v\f\r", v[i]) >= 0 {
		i++
	}
	neg := false
	if i < len(v) && (v[i] == '+' || v[i] == '-') {
		neg = v[i] == '-'
		i++
	}
	start := i
	var n int64
	sat := false
	for ; i < len(v) && v[i] >= '0' && int64(v[i]-'0') < base; i++ {
		d := int64(v[i] - '0')
		if n > (math.MaxInt64-d)/base {
			sat = true
		} else if !sat {
			n = n*base + d
		}
	}
	if i == start {
		return 0, v
	}
	switch {
	case sat && neg:
		n = math.MinInt64
	case sat:
		n = math.MaxInt64
	case neg:
		n = -n
	}
	return n, v[i:]
}

// colorParses is Git's color_parse_mem: words separated by Git
// whitespace; "reset"; up to two colors (normal, default, #rrggbb,
// black..white with an optional "bright" prefix, a number from -1 to
// 255); attributes bold, dim, italic, ul, blink, reverse, strike, each
// optionally prefixed by "no" or "no-". Empty is the empty color.
func colorParses(v string) bool {
	colors := 0
	for _, w := range strings.FieldsFunc(v, func(r rune) bool { return r == ' ' || r == '\t' || r == '\n' || r == '\r' }) {
		switch {
		case strings.EqualFold(w, "reset"):
		case isColorName(w):
			if colors++; colors > 2 {
				return false
			}
		case isColorAttr(w):
		default:
			return false
		}
	}
	return true
}

func isColorName(w string) bool {
	if strings.EqualFold(w, "normal") || strings.EqualFold(w, "default") {
		return true
	}
	if len(w) == 7 && w[0] == '#' {
		ok := true
		for i := 1; i < 7; i++ {
			ok = ok && hexDigit(w[i]) >= 0
		}
		if ok {
			return true
		}
	}
	name := w
	if len(name) > 6 && strings.EqualFold(name[:6], "bright") {
		name = name[6:]
	}
	for _, c := range []string{"black", "red", "green", "yellow", "blue", "magenta", "cyan", "white"} {
		if strings.EqualFold(name, c) {
			return true
		}
	}
	n, rest := strtol(w, 10)
	return rest == "" && n >= -1 && n < 256
}

func isColorAttr(w string) bool {
	if rest, ok := strings.CutPrefix(w, "no"); ok {
		w = strings.TrimPrefix(rest, "-")
	}
	switch w {
	case "bold", "dim", "italic", "ul", "blink", "reverse", "strike":
		return true
	}
	return false
}
